const imageArray = [
 
  { id: 17, image: "/carousel/17.jpg" },
  { id: 18, image: "/carousel/18.jpg" },
  { id: 19, image: "/carousel/19.jpg" },
  { id: 20, image: "/carousel/20.jpg" },
  { id: 21, image: "/carousel/21.jpg" },
  { id: 22, image: "/carousel/22.jpg" },
  { id: 23, image: "/carousel/23.jpg" },
  { id: 24, image: "/carousel/24.jpg" },
  { id: 25, image: "/carousel/25.jpg" },
  { id: 26, image: "/carousel/26.jpg" },
  { id: 27, image: "/carousel/27.jpg" },
  { id: 28, image: "/carousel/28.jpg" },
  { id: 29, image: "/carousel/29.jpg" },
  { id: 30, image: "/carousel/30.jpg" },
  { id: 31, image: "/carousel/31.jpg" },
  { id: 32, image: "/carousel/32.jpg" },
  { id: 33, image: "/carousel/33.jpg" },
  { id: 34, image: "/carousel/34.jpg" },
  { id: 35, image: "/carousel/35.jpg" },
  { id: 36, image: "/carousel/36.jpg" },
  { id: 37, image: "/carousel/37.jpg" },
  { id: 38, image: "/carousel/38.jpg" },
  { id: 39, image: "/carousel/39.jpg" },
  { id: 40, image: "/carousel/40.jpg" },
  { id: 41, image: "/carousel/41.jpg" },
  { id: 42, image: "/carousel/42.jpg" },
  { id: 43, image: "/carousel/43.jpg" },
  { id: 44, image: "/carousel/44.jpg" },
  { id: 45, image: "/carousel/45.jpg" },
  { id: 46, image: "/carousel/46.jpg" },
  { id: 47, image: "/carousel/47.jpg" },
  { id: 48, image: "/carousel/48.jpg" },
  { id: 49, image: "/carousel/49.jpg" },
  { id: 50, image: "/carousel/50.jpg" },
  { id: 51, image: "/carousel/51.jpg" },
  { id: 52, image: "/carousel/52.jpg" },

];

export default imageArray;

